### ISSUE TITLE
Wrong Exception Message in Transactions

### ISSUE THREAD

**Issue by shiva-6** [googleapis/java-firestore#1183]
I understand internally we use writebatch for transactions but the error messages should be related to feature. So, If I was using transactions outside the method, It throws an exception but saying writebatch has been already commited rather than saying transaction.

#### Environment details

1. API : runTransaction
2. OS type and version: windows11
3. Java version: 1.8
4.  version(s):

#### Steps to reproduce

  1. I have added sample code, Please check to reproduce the issue

#### Code example

```java
// example
   public static void solve() {
        // Create your client
        // Firestore firestoreClient = 
        Transaction t = null;
        try {
            t = firestoreClient.runTransaction(transaction -> {
                // do something
                return transaction;
            }).get();
            t.get(firestoreClient.document("users/me"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

#### Stack trace
java.lang.IllegalStateException: Cannot modify a WriteBatch that has already been committed. at com.google.common.base.Preconditions.checkState(Preconditions.java:502) at com.google.cloud.firestore.UpdateBuilder.verifyNotCommitted(UpdateBuilder.java:158) at com.google.cloud.firestore.UpdateBuilder.performUpdate(UpdateBuilder.java:519) at com.google.cloud.firestore.UpdateBuilder.update(UpdateBuilder.java:356)

**Comment by dconeybe** [comment]
Thank you for this bug report. I'll take a look and see what we can do.

**Comment by shiva-6** [comment]
@dconeybe any update on this?

**Comment by dconeybe** [comment]
No update yet. Is this causing you issues? I've prioritized it low compared to other work because my understanding was that this is purely cosmetic, in that you'd like to see a better error message, but does not affect functionality at all. Is that understanding correct?
