### ISSUE TITLE
Add toString methods to classes comprising WriteBatch

### ISSUE THREAD

**Issue by eranl** [googleapis/java-firestore#1280]
For development, it would be very helpful to have toString methods on classes comprising WriteBatch. It would make it easier to see the data in the debugger and log it in dry-run mode.

**Comment by MarkDuckworth** [comment]
@eranl, can you tell me more about the challenge you are facing when debugging and how you would prefer to use toString to help? Knowing a little more will help us prioritize the request. Thanks!

**Comment by tom-andersen** [comment]
Thank you for the PR. I think this is a great addition, and I hope to see you follow through on our process. Please see comments in PR. There is a strict style guide, but that is easily overcome with a script that formats code for you.

We need test coverage for any changes, so once we have unit tests in place, I think we are ready to merge!
