### ISSUE TITLE
Actual types passed to generic POJO super classes and to generic collection fields are ignored

### ISSUE THREAD

**Issue by eranl** [googleapis/java-firestore#1313]
Given the classes
```java
  private static class BaseBean<T> {
    public T value;
  }

  private static class SubBean extends BaseBean<String> {}
```
if you try to deserialize into the sub-bean, you get `java.lang.IllegalStateException: Could not resolve type T`. Same is true for a base bean with a setter that takes a T parameter.

While debugging this, I found that given the classes
```java
  private static class MapBean<T> {
    public Map<String, T> values;
  }

  private static class MapSubBean extends MapBean<String> {}

  private static class MapBeanHolder {
    public MapBean<String> map;
  }
```
deserializing into MapSubBean or MapBeanHolder, the code errs on the lenient side, and would accept any type of values into the `values` map.

I have a proposed fix for both issues. Should I post a PR? The collection part of the fix might break existing code, so it may need to be excluded.

**Comment by tom-andersen** [comment]
Hello again @eranl!

If a feature is important to you, then submitting a PR will certainly accelerate the process. We are adverse to breaking changes, and will only consider them for major releases. So if we can steer clear of anything that can break code, that will make accepting the PR much easier.

Thanks!

**Comment by eranl** [comment]
Hi @tom-andersen,

Will do. Actually, in my PR, I will introduce a new `@StrictCollectionTypes` annotation, and use that to add the fix in a backward-compatible way.

**Comment by tom-andersen** [comment]
Thanks! I will take a closer look.

**Comment by eranl** [comment]
Hi @tom-andersen, any update?

**Comment by tom-andersen** [comment]
I have created an internal ticket to track this feature request. b/314353099
