### ISSUE TITLE
Support @PropertyName on Setters only

### ISSUE THREAD

**Issue by olssonoskar** [googleapis/java-firestore#159]
**Issue**
Currently in a project where we develop a service that wants to consume data from Firestore. The fields are named differently in firestore than we want them so we use @PropertyName to change them during deserialization. Since we only care about deserialization (we never write something back to firestore) I assumed that it would be enough to write setters with the annotation for this to work. This is not the case, since properties will be added by variable name (in this case because of getters without the annotation) and since the setters with annotation are not matching these, they will be ignored. So to have working deserialization it seems to be a requirement to have getters with the same annotation? The small issue this results in is that you can't generate the getters with something like lombok, instead you have to write the getters and include the same annotation.

**Expected**
Since we only care about creating the objects, I expected annotated setters to be enough to support the renaming from firestore to our POJO. Instead, the setters are ignored because the getters without annotation add properties with non-matching names. This is because there are no existingPropertyName matching the setters annotated value.

**Finally**
This is more of a quality of life improvement and not a dealbreaker. Also there might be a reason why getters with @PropertyName is required, or something else I have misunderstood. If so, an explanation to clarify why this is the case would be appreciated!

**Comment by BenWhitehead** [comment]
@schmidt-sebastian Do you have context or know someone who does about the existing priority of fields over setters?
