### ISSUE TITLE
Avoid excessive logging of missing setters

### ISSUE THREAD

**Issue by vojkny** [googleapis/java-firestore#1663]
We are seeing a lot of these in our logs:

```
WARNING: No setter/field for freeMessage found on class hero.model.Post (fields/setters are case sensitive!)
Apr 28, 2024 9:35:49 PM com.google.cloud.firestore.CustomClassMapper$BeanMapper deserialize
WARNING: No setter/field for empty found on class hero.model.PostAsset (fields/setters are case sensitive!)
Apr 28, 2024 9:35:49 PM com.google.cloud.firestore.CustomClassMapper$BeanMapper deserialize
WARNING: No setter/field for freeMessage found on class hero.model.Post (fields/setters are case sensitive!)
Apr 28, 2024 9:35:49 PM com.google.cloud.firestore.CustomClassMapper$BeanMapper deserialize
WARNING: No setter/field for empty found on class hero.model.PostAsset (fields/setters are case sensitive!)
Apr 28, 2024 9:35:49 PM com.google.cloud.firestore.CustomClassMapper$BeanMapper deserialize
WARNING: No setter/field for freeMessage found on class hero.model.Post (fields/setters are case sensitive!)
Apr 28, 2024 9:35:49 PM com.google.cloud.firestore.CustomClassMapper$BeanMapper deserialize
```

It was also reported here: https://github.com/googleapis/java-firestore/issues/524

The solution is to annotate the class with `@IgnoreExtraProperties` - however we would have to annotate tens of classes and we also don't want to add such dependency into our Model.

Would it be possible to add some ENV var which would allow to disable such log?

**Comment by milaGGL** [comment]
Hi @vojkny, thank you for reporting this issue. After team discussion, we decided adding a new ENV variable is not something we would want for the time being. Addressing the warnings by adding the necessary fields/setters is a more suitable approach if you do not wish to use annotations.
