### ISSUE TITLE
Update gRPC to 1.64.0

### ISSUE THREAD

**Issue by larssn** [googleapis/java-firestore#1708]
I'm not sure how to make a pull request for this, as it seems to be defined in the maven artifact `first-party-dependencies`: https://central.sonatype.com/artifact/com.google.cloud/first-party-dependencies

We've seen a lot of "internal errors" lately downstream, in Flutter, which it's my understanding stems from gRPC.

So here's a request to update to the latest version of gRPC, which as of writing is `1.64.0`.

The exact error: `[cloud_firestore/internal] Internal errors. Means some invariants expected by underlying system has been broken. If you see one of these errors, something is very broken.`

**Comment by ehsannas** [comment]
Flutter is built on top of the Android SDK. This repo is the java server client. I see that you have also filed an issue in the Android SDK repo, so I will close this.
