### ISSUE TITLE
Retry triggered for ever failing errors

### ISSUE THREAD

**Issue by lpellegr** [googleapis/java-firestore#203]
For the sake of explanation, let's say you have a transaction that includes a simple call to create a document. If the create operation fails because the document ID already exists, then a `com.google.api.gax.rpc.AlreadyExistsException` is thrown and the transaction is retried again and again until to reach the default retry threshold. At this stage, the original cause/exception is wrapped in a generic `com.google.cloud.firestore.FirestoreException` with code `ABORTED`.

In that case, would that not make sense to stop immediately and prevent the retry mechanism?

I cannot find documentation about this case. Is there a technical reason? I would be interested to know more :)

**Comment by BenWhitehead** [comment]
@schmidt-sebastian You are familiar with the transaction retry logic matrix, can you chime in here?

**Comment by schmidt-sebastian** [comment]
@lpellegr I think this is an oversight. We ported the retry codes from our Mobile SDKs, where `AlreadyExistsException` is not thrown due to its lack of `create()`. I will send a PR shortly.

**Comment by schmidt-sebastian** [comment]
Actually, I was wrong: We define the codes that we want to retry on and for that, the list of codes for the Server SDKs and the Mobile SDKs match.

@lpellegr Can you verify that you are on the most recent version of the SDK? We just revamped our retry behavior and if I read our code correctly we should no longer retry on ALREADY_EXISTS. See here: https://github.com/googleapis/java-firestore/blob/00b6eb3703c8f4942d6da42b827ecbeeb9a13ef5/google-cloud-firestore/src/test/java/com/google/cloud/firestore/TransactionTest.java#L452

**Comment by lpellegr** [comment]
Oops, I was using version `1.32.5`. Upgrading to `1.33.0` has resolved the problem. Sorry for the inconvenience.
