### ISSUE TITLE
IN queries

### ISSUE THREAD

**Issue by achuinard** [googleapis/java-firestore#27]
Most Firestore clients now support this, but I see no progress made on the Java side. Is this coming soon?

**Comment by BenWhitehead** [comment]
The `IN` & `ARRAY_CONTAINS_ANY` query filters were released in version `1.29.0` back at the end of October.

Code samples can be found published in the official docs here: https://cloud.google.com/firestore/docs/query-data/queries#in_and_array-contains-any
Javadocs can be found published here: [`whereIn`](https://googleapis.dev/java/google-cloud-clients/latest/index.html?com/google/cloud/firestore/package-summary.html) [`whereArrayContainsAny`](https://googleapis.dev/java/google-cloud-clients/latest/index.html?com/google/cloud/firestore/package-summary.html)

**Comment by achuinard** [comment]
My mistake! I need to bug the `firebase-admin-java` guys to update their dependency version.
