### ISSUE TITLE
Temporary animal-sniffer-annotations exclusion rules in poms.

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/java-firestore#33]
As of `grpc-api:1.25.0` and `guava:28.1-android` there is a failure for `animal-sniffer-annotations`
```
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.codehaus.mojo:animal-sniffer-annotations:1.17 paths to dependency are:
+-com.google.api.grpc:grpc-google-cloud-firestore-admin-v1:1.32.0
  +-io.grpc:grpc-api:1.25.0
    +-org.codehaus.mojo:animal-sniffer-annotations:1.17
and
+-com.google.api.grpc:grpc-google-cloud-firestore-admin-v1:1.32.0
  +-com.google.guava:guava:28.1-android
    +-org.codehaus.mojo:animal-sniffer-annotations:1.18
]
```
There is no actual difference between the single annotation present in the versions, so it is being excluded for the time being.

The exclusion should be removed from the poms when there is no longer a disparity.

**Comment by elharo** [comment]
FYI, Guava 28.2 no longer depends on animal-sniffer-annotations. It should also be possible to remove that dependency from other artifacts where it appears.
