### ISSUE TITLE
Is this library suitable for Java client apps with firestore?

### ISSUE THREAD

**Issue by ScottPierce** [googleapis/java-firestore#461]
Is this library suitable for use with Java client side applications for pairing with Firestore? Firebase seems to offer a firestore java admin library, but I'm looking for a library that will work with java clients (as in a customer facing application), allow me to authenticate, and not bypass firebase security rule restrictions on the database. The documentation for this library isn't super clear, but will this library meet my needs?

**Comment by wu-hui** [comment]
The short answer to your question is no, unfortunately.

The SDK is intended for backend usage, ie you have a backend service (web server for example) that connects to Firestore on user behalf, hence it will not enforce security rule checks. In fact, the Admin SDK you mentioned is a wrapper of this SDK.

Are you building a desktop App using Java? If so, the closest thing to what you described is probably Firebase CPP SDK (https://firebase.google.com/docs/cpp/setup#desktop-workflow). It is a client SDK so it has security rule checks. But it's CPP, and you have to use it from JNI, and the SDK itself is still in Alpha.

Another possibility is use the client JS/Web(Not server side Node) SDK as a Node library. It is not officially supported, and you might need to jump a few hoops to make it work, but it should be possible.

If you only target Apple platforms, using the iOS SDK is also possible.

But as I mention, none of these works out of the box for a Java App, and you will need to make the right choice for yourself.

**Comment by ScottPierce** [comment]
@wu-hui So so this won't work because it's authenticating with the firebase server as an admin. How difficult do you think it'd be for me to modify this library and add the authentication necessary to authenticate a client so that the security rules were followed?

**Comment by wu-hui** [comment]
Hmm..if you are considering this, then you probably don't need the offline cache support anyways. I'd look into REST api first: https://firebase.google.com/docs/firestore/use-rest-api

This will follow security rules. You'd need to build the SDK yourself though.

**Comment by ScottPierce** [comment]
@wu-hui I can't use the REST api because I need notifications when data is changed, and I believe the REST api doesn't support realtime queries. My primary goal in using the firebase offline mode / cache would be to cost savings.

Let me ask you a quick question about how smart the cache is. Let's say I perform a real-time query and 20 entities are returned from the server.
1. If I perform the same query an hour later, will I be charged for 20 reads? I'm assuming I would be. Even if the data is cached, the server would still need to return 20 objects from the database to ensure that the data I have is up-to-date, right?
2. How smart is the cache? Or is the cache really only good for offline use?

**Comment by wu-hui** [comment]
Before I answer your questions, I want to point out the the Java SDK (this repo) does not have support for offline/cache, this is a SDK designed for server side usage. If you really need that (and security rules), your best bet is the C++ or JS (but used as Node) SDK, as I explained above. If Firestore is a vital part of your App, I'd consider making it a Node App instead, IMHO.

That being said, let me answer your questions. Note they are big questions, I'll try to give thorough answers:

1. If you perform the same query with default query options, you will be charged for those 20 reads. There are ways to specify the query to return results from local cache only, which saved you the read, but obviously you might have stale data. You could also keep the query "alive", so after the initial charges, the deltas/updates to the query can be potentially saved. 

2. What usage you have in mind? It can be used in complete offline cases, but it is not designed to perform well if you have a lot of documents cached locally. It is designed to be a cache working with backend queries and raise real time snapshots quickly.

**Comment by ScottPierce** [comment]
> I want to point out the the Java SDK (this repo) does not have support for offline/cache

My goal in asking the questions was to ensure that I don't actually need the cache for my use-case. A few years ago I got the impression that once a document was cached, you were never charged to read that document from any query ever again unless that document changed. I'm assuming I misunderstood an explanation of a live query delta changes. I was double checking that I in fact don't need the cache to keep firebase costs low, because I don't think they will actually save that much money.

> You could also keep the query "alive", so after the initial charges, the deltas/updates to the query can be potentially saved.

Receiving only deltas is also possible with this library right?

What I really need from firestore is a scalable managed database that allows me to make live queries to be notified when another linked client saves something to the database.

**Comment by wu-hui** [comment]
> Receiving only deltas is also possible with this library right?

Yes.

> What I really need from firestore is a scalable managed database that allows me to make live queries to be notified when another linked client saves something to the database.

But you also want security rules right? This is what this SDK does not offer. At the end of the day, it is your decision to make. Unfortunately, Java desktop App is not officially supported, so regardless your choice you should probably prepare for some bumpiness. Happy to answer more questions along the way.

**Comment by ScottPierce** [comment]
By forking this library and logging in normally, instead of with admin credentials, wouldn't security rules be applied to all activity? I'm assuming security rules are enforced by the server.

**Comment by wu-hui** [comment]
Unfortunately, the answer would be maybe. The system behind SDK is complex, and I cannot give you a definitive answer without dive into the backend. Also, even if you make this work now, future updates might change it, because it is not officially supported, this is something you need to consider as well.

**Comment by ScottPierce** [comment]
I'm investigating an alternative of just using the firestore rest api, and cloud pub/sub to notify clients of changes. I'm not seeing any information around pub/sub being usable from clients though, making me think it might only supposed to be used on the server as well :\

**Comment by ScottPierce** [comment]
> Also, even if you make this work now, future updates might change it, because it is not officially supported, this is something you need to consider as well.

Really? This seems odd to me. Aren't you guys just using the documented contract in the Cloud Firestore API - https://firebase.google.com/docs/firestore/reference/rpc
