### ISSUE TITLE
Set CustomClassMapper.warnOnUnknownProperties

### ISSUE THREAD

**Issue by vojkny** [googleapis/java-firestore#524]
I am seeing a lot of logs like:

```
WARNING: No setter/field for count found on class User
Feb 03, 2021 8:23:06 AM com.google.cloud.firestore.CustomClassMapper$BeanMapper deserialize
````

While studying the code, it seems this can be disabled with `warnOnUnknownProperties`. However, there is no documentation and no comments how to set this field. Can sb pls elaborate?

**Comment by lizell** [comment]
I found the solution to this, @knyttl 

You will have to annotate the class you are deserializing with the `@IgnoreExtraProperties` annotation from `com.google.cloud.firestore.annotation.IgnoreExtraProperties` like:

```java
@IgnoreExtraProperties
public class Something {
    ...
}
```

**Comment by knyttl** [comment]
I ended up forking the firestore and commenting out the whole logging part. I new this annotation but didn't want to annotate everything with it.

**Comment by vojkny** [comment]
> I found the solution to this, @knyttl
> 
> You will have to annotate the class you are deserializing with the `@IgnoreExtraProperties` annotation from `com.google.cloud.firestore.annotation.IgnoreExtraProperties` like:
> 
> ```java
> @IgnoreExtraProperties
> public class Something {
>     ...
> }
> ```

I recreated a new issue for this, because it is still a problem for us.
