### ISSUE TITLE
How to know avaliable urls in Google Cloud Emulator Firestore?

### ISSUE THREAD

**Issue by 1Wggb1** [googleapis/java-firestore#550]
I´m learning to how to use google cloud emulator firestore, however i would know how can i know the avaliable urls to interact with emulator. I only managed access this url: http://localhost:port/emulator/v1/projects/project-id:ruleCoverage.html.
Are there some command than i can know about this? Or Are there some UI to access?

**Comment by BenWhitehead** [comment]
Hi @1Wggb1,

The Cloud Firestore Emulator provides a local implementation of the Cloud Firestore API. Reference docs for the API can be found here: https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1

That API is lower level than the api provided by [`com.google.cloud.firestore.Firestore`](https://googleapis.dev/java/google-cloud-firestore/latest/com/google/cloud/firestore/Firestore.html) which can be found in this repo. Quickstart docs for the `com.google.cloud.firestore.Firestore` API can be found here: https://cloud.google.com/firestore/docs/quickstart-servers#java
