### ISSUE TITLE
Sorted function

### ISSUE THREAD

**Issue by luluxe** [googleapis/java-firestore#566]
Hello,

I didn't find a feature that I think is indispensable.
Be able to sort the result on a CollectionReference listDocumentsSorted(String attribute, boolean desc: false)

If the function already exists, tell me where I couldn't find it.

Looks,
Lucas.

**Comment by crwilcox** [comment]
I think you are looking for `orderBy`
https://firebase.google.com/docs/firestore/query-data/order-limit-data#java_3
