### ISSUE TITLE
Firestore Java: Can't cancel a query from ApiStreamObserver

### ISSUE THREAD

**Issue by icoloma** [googleapis/java-firestore#574]
I want to implement an in-memory filter for a query (to reduce the number of indexes on Firestore, but also to implement features like fuzzy search) in places where I know that the number of query results is small, like hundreds but not thousands. I want to return results with a paged query: starting with a cursor, filter in memory until I have enough results to return a page or there are no more results. 

I cannot do this with the current streaming implementation in Firestore SDK. What I am trying is: 

* Create a query with a big limit, say 1000
* Start streaming
* When I have enough values for a page, collect the page contents and next cursor, and return inside an `ApiFuture`:

```Java
// the CursorList class to return after filtering in memory
public class CursorList<T> {

  List<DocumentSnapshot> data;
  String cursor;

}

// prime up the test
var collection = FirestoreSingleton.getInstance().collection("Test");
collection.document("0").create(Map.of("order", 0)).get();
collection.document("1").create(Map.of("order", 1)).get();
collection.document("2").create(Map.of("order", 2)).get();
var query = collection.orderBy("order", Query.Direction.ASCENDING).limit(1000);

// run the in-memory filter
final int pageSize = 10;
final List<DocumentSnapshot> filteredResult = Lists.newArrayListWithExpectedSize(pageSize);
final SettableApiFuture<CursorList> future = SettableApiFuture.create();

query.stream(
  new ApiStreamObserver<DocumentSnapshot>() {
    DocumentReference cursor = null;

    private boolean passes(DocumentSnapshot value) {
      // Dummy in-memory filter implementation
      return value.get("order") % 2 == 0;
    }

    @Override
    public void onNext(DocumentSnapshot value) {
      if (passes(value)) {
        if (filteredResult.size() < pageSize) {
          filteredResult.add(instance);
        } else {
          cursor = value.getReference();
          triggerResult();

          //
          // TODO: I'd like to also cancel the streaming, 
          // but it's not possible 
          //

        }
      }
    }

    @Override
    public void onError(Throwable t) {
     future.setException(t);
    }

    private void triggerResult() {
      future.set(new CursorList(filteredResult, cursor));
    }

    @Override
    public void onCompleted() {
      triggerResult();
    }
  }
);
return future;
```

With the current implementation, an `ApiStreamObserver` cannot cancel the execution of a query, which will keep going until 1000 results (or whatever limit I set) have been processed, even if the future has already been resolved. 

Did I miss something?  From what I could see, there is a [`StreamObserver`](https://github.com/grpc/grpc-java/issues/3095) that I could use to cancel a stream in GRPC, but Firestore is not supporting that. I can ditch streaming and use batches of queries, but it would be less efficient and a messier implementation.

Any help is welcome.

**Comment by wu-hui** [comment]
Sorry for replying late.

Pagination is typically done with `limit`/`limitToLast`/`startAt`/`endAt` queries. See: https://googleapis.dev/java/google-cloud-firestore/latest/index.html

Also see: https://firebase.google.com/docs/firestore/query-data/query-cursors#java_1 for some examples.

Hope this helps!

**Comment by icoloma** [comment]
@wu-hui This does not help. The main issue is that I do not know the size of the pages in advance, because I need to do some filtering using my own code that cannot be done on Firestore indexes (for example, fuzzy search or regexp). This leaves me with two choices:

* Iterate through multiple pages in memory, until I have enough filtered items to return a results page. Since each page returned by Firestore reads all results in memory in a `List`, I need to keep the page size reasonable. 
* Use `ApiStreamObserver` and process results one by one until I have enough to return a results page. This would be preferable because the implementation is simpler (see example above), but I have no way to stop the stream when I have completed a page. 
 
Both cases return both the page of results (filtered in memory, using my own code) and the cursor to continue searching. With the current status of the SDK, option 2 does not seem possible.

**Comment by wu-hui** [comment]
Hey @icoloma 

Sorry for not closing the issue without fully understanding your requirement. 

Unfortunately this is not supported currently. I can see we support it in the future, but I cannot say when will this happen. 

I created an internal issue to track this, and I will try to report back here when we do have a timeline.
