### ISSUE TITLE
Missing JavaDoc for "FirestoreBundle"

### ISSUE THREAD

**Issue by samtstern** [googleapis/java-firestore#579]
#### Environment details

N/A

#### Steps to reproduce

Browsing the JavaDoc here:
https://googleapis.dev/java/google-cloud-firestore/latest/index.html?com/google/cloud/firestore/Firestore.html

I don't see docs for this class:
https://github.com/googleapis/java-firestore/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreBundle.java

And it actually looks like the latest ref docs are for version 1.35.2 which is 9 months old:
https://github.com/googleapis/java-firestore/releases/tag/v1.35.2

#### Code example

N/A

#### Stack trace

N/A

#### External references such as API reference guides

See above.

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by samtstern** [comment]
cc @markarndt

**Comment by meredithslota** [comment]
It looks like this has been corrected — I see https://googleapis.dev/java/google-cloud-firestore/latest/index.html?com/google/cloud/firestore/Firestore.html which includes `Class FirestoreBundle` in the sidebar, and I see docs for all the latest versions. I suspect we hit a docgen issue awhile ago that got resolved for all Java libraries.
