### ISSUE TITLE
Update documentations to include information on thread safety.

### ISSUE THREAD

**Issue by maen-allaga** [googleapis/java-firestore#663]
Hi there,
I was looking at multi-threading app using Cloud Firestore, I'm not sure if the `Firestore` object is thread safe. Is it using connection pooling? are there any internal state that prevents using it in a multi-threaded application?
Please update the documentations to include such info.

Thanks!

**Comment by wu-hui** [comment]
Make our SDKs safe to use with multiple threads is assumed and therefore not documented. You can use the SDK from different threads.

If you do encounter concurrency issues around the SDK, please do let us know here!
