### ISSUE TITLE
Error handling documenation

### ISSUE THREAD

**Issue by happytomatoe** [googleapis/java-firestore#678]
Hello. 
I am writing code to retry a transaction in case of failure and currently, I don't know to identify which exceptions should be retried. 
I found that datastore has an error handling section which is very helpful but I didn't found such a section for firestore. 
Thanks

**Comment by dmahugh** [comment]
Thanks for the feedback. I assume this is the Datastore doc page you're referring to, correct? [https://cloud.google.com/datastore/docs/concepts/errors](https://cloud.google.com/datastore/docs/concepts/errors)

**Comment by jlara310** [comment]
Hi,

The Firestore version of this table is here:
https://cloud.google.com/firestore/docs/use-rest-api#error_codes

Note that the guidance is mostly the same.

**Comment by babkamen** [comment]
@dmahugh Yes, you are correct.
@jlara310 Thanks for the info. Are there differences?
 
It would be good to have an example of how to retry a transaction.

**Comment by meredithslota** [comment]
It's my understanding that the Firestore clients automatically retry failed transactions as per https://cloud.google.com/firestore/docs/best-practices#transactions_retries — have you found this not to be true?
