### ISSUE TITLE
Fix Javadoc generation

### ISSUE THREAD

**Issue by kolea2** [googleapis/java-firestore#724]

**Comment by craiglabenz** [comment]
One item waiting on this is the appearance of [Bundle](https://github.com/googleapis/java-firestore/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreBundle.java) instructions on the [public docs page](https://googleapis.dev/java/google-cloud-firestore/latest/com/google/cloud/firestore/Firestore.html).
