### ISSUE TITLE
Permission Issue when using listCollection()

### ISSUE THREAD

**Issue by the-lion-king08** [googleapis/java-firestore#819]
Code: Iterable<CollectionReference> collections =
				    db.collection("Test").document("Test1").listCollections();

Error: PERMISSION_DENIED: Missing or insufficient permissions.

Want to list all sub-collection in Test1. 

Security Rule: 
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}

The service account that I am using has the firebase admin role.

**Comment by wu-hui** [comment]
Hi @the-lion-king08 

Is this still a problem? You are using the Java SDK as admin, and your security rule allows general read and write. Are you sure you used the right admin user to access?

**Comment by the-lion-king08** [comment]
Hi @wu-hui 

Thanks for replying.

Actually, I was using cloud firestore java sdk for auth. And when I used the firebase admin sdk it worked.
