### ISSUE TITLE
Timestamp to LocalDateTime ?

### ISSUE THREAD

**Issue by fgruchala** [googleapis/java-firestore#88]
Hi team,

I want to use the LocalDateTime object and it doesn't seems to have a native (de)serializer, right ?
The only way I see is to use the basic Date object.

Do you confirm ? Is it plan in your roadmap ?

Thanks a lot for your answer,
François

**Comment by BenWhitehead** [comment]
Hi François,

Today it is not yet possible for us to support `java.time.LocalDateTime` as our current minimum supported JDK is 1.7 as such we do not have access to `LocalDateTime`.

Unfortunately I don't have a timeframe for when our minimum supported JDK will bump up to 1.8 and allow for this feature to be implemented. I do believe this is something that would be an improvement for our libraries when we're able to accommodate it.

**Comment by fgruchala** [comment]
Hi,

Thanks for your reply.
It's interesting and I understand, no problem.

Have a good day,

Le jeu. 30 janv. 2020 à 20:13, BenWhitehead <notifications@github.com> a
écrit :

**Comment by knyttl** [comment]
Actually, when using Jackson, one can use custom serializers/deserializers - in this case:

```
val objectMapper = ObjectMapper()
    .registerModule(JavaTimeModule())
```

Ideally such custom serializer could be inside a different optional module with Java8 scope which would allow using LocalDateTime or Instant. Jackson basically behaves the same.

**Comment by huw0** [comment]
It would be good to understand why this issue has been closed?

If a manual workaround is required, it would be helpful for this to remain open. If not, it would be good to confirm the release where this improvement was added.

**Comment by knyttl** [comment]
Why was this closed? Can you justify it?

**Comment by knyttl** [comment]
I created a new clean and more descriptive issue: https://github.com/googleapis/java-firestore/issues/509

**Comment by knyttl** [comment]
For anyone interested, I forked the repo and replaced the Timestamp implementation with java8's `java.time.Instant` one:

https://github.com/knyttl/java-firestore/commits/instant

This can be linked via [JitPack](https://jitpack.io/#knyttl/java-firestore/instant-SNAPSHOT) repository:

`implementation com.github.knyttl.java-firestore:google-cloud-firestore:hero-SNAPSHOT`
